In [1]:
!pip -q install pymysql sqlalchemy

In [2]:
!pip install "sqlalchemy<2.0" -q

In [2]:
# prepare SQL environment
%load_ext sql

In [3]:
#mysql connection string
%sql mysql+pymysql://root:37882792@127.0.0.1:3306/md_water_services

'Connected: root@md_water_services'

In [8]:
pip install prettytable==3.6.0

Collecting prettytable==3.6.0Note: you may need to restart the kernel to use updated packages.

  Downloading prettytable-3.6.0-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: wcwidth in c:\users\vince\anaconda3\lib\site-packages (from prettytable==3.6.0) (0.2.5)
Downloading prettytable-3.6.0-py3-none-any.whl (27 kB)
Installing collected packages: prettytable
  Attempting uninstall: prettytable
    Found existing installation: prettytable 3.16.0
    Uninstalling prettytable-3.16.0:
      Successfully uninstalled prettytable-3.16.0
Successfully installed prettytable-3.6.0

In [5]:
%%sql
select * from 
    md_water_services.global_water_access
limit 10;

 * mysql+pymysql://root:***@127.0.0.1:3306/md_water_services
10 rows affected.

[('Afghanistan', 'South Asia', 2015, 34413.6, 24.803, 61.3398, 3.5112, 22.1688, 12.9802, 52.9885, 3.86114, 26.5533, 16.5971, 86.6589, 2.45027, 8.87604, 2.01475),
 ('Afghanistan', 'South Asia', 2020, 38928.3, 26.026, 75.0914, 1.44754, 14.5603, 8.90078, 66.3279, 1.95682, 19.6829, 12.0323, 100.0, 0.0, 0.0, 0.0),
 ('Albania', 'Europe & Central Asia', 2015, 2890.52, 57.434, 93.3943, 3.62638, 2.97929, 0.0, 90.6273, 5.26317, 4.10955, 0.0, 95.4451, 2.41331, 2.14162, 0.0),
 ('Albania', 'Europe & Central Asia', 2020, 2877.8, 62.112, 95.068, 1.88466, 3.04731, 0.0, 94.0914, 2.30526, 3.60338, 0.0, 95.6638, 1.62809, 2.7081, 0.0),
 ('Algeria', 'Middle East & North Africa', 2015, 39728.0, 70.848, 93.4096, 5.15778, 1.27546, 0.157193, 88.3527, 8.68575, 2.58043, 0.381108, 95.4903, 3.70612, 0.73851, 0.0650579),
 ('Algeria', 'Middle East & North Africa', 2020, 43851.0, 73.733, 94.4373, 4.98588, 0.531837, 0.0449525, 90.0375, 8.79672, 0.994603, 0.171137, 96.0047, 3.62829, 0.366976, 0.0),
 ('American Samoa', 'East Asia & Pacific', 2015, 55.806, 87.238, 99.6191, 0.0, 0.380897, 0.0, None, None, None, None, None, None, None, None),
 ('American Samoa', 'East Asia & Pacific', 2020, 55.197, 87.153, 99.7738, 0.0, 0.226228, 0.0, None, None, None, None, None, None, None, None),
 ('Andorra', 'Europe & Central Asia', 2015, 77.993, 88.345, 100.0, 0.0, 2.44554e-06, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0),
 ('Andorra', 'Europe & Central Asia', 2020, 77.265, 87.916, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0)]